import asyncio
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from fastapi.exceptions import RequestValidationError
from sqlalchemy.exc import SQLAlchemyError
from redis.exceptions import ConnectionError as RedisConnectionError, RedisError
from core.logger import logger

def register_exception_handlers(app: FastAPI):   
    @app.exception_handler(RequestValidationError)
    async def validation_exception_handler(request: Request, exc: RequestValidationError):
        """
            Custom exception handler for validation errors.
            
            Catches 422 Unprocessable Entity errors generated by Pydantic validation,
            cleans up the default error message by removing the "Value error, " prefix,
            and returns a cleaner JSON response to the client.
        """
        error_msg = exc.errors()[0].get("msg", "")
        clean_msg = error_msg.replace("Value error, ", "") 
        return JSONResponse(
            status_code=422,
            content={
                "detail": clean_msg
                }
        )

    @app.exception_handler(ValueError)
    async def value_error_exception_handler(request: Request, exc: ValueError):
        logger.warning(f"Business logic error caught: {exc}")
        return JSONResponse(
            status_code=400,
            content={
                "detail": str(exc)
            }
        )

    @app.exception_handler(SQLAlchemyError)
    async def sqlalchemy_exception_handler(request: Request, exc: SQLAlchemyError):
        logger.error(f"Database error globally caught: {exc}")
        return JSONResponse(
            status_code=503,
            content={
                "detail": "Entschuldigung, es gibt derzeit ein Problem mit dem Server. Bitte versuche es später noch einmal."
                }
        )

    @app.exception_handler(RedisConnectionError)
    async def redis_connection_exception_handler(request: Request, exc: RedisConnectionError):
        logger.error(f"Redis connection error globally caught: {exc}")
        return JSONResponse(
            status_code=503,
            content={
                "detail": "Das System ist derzeit stark ausgelastet. Bitte versuche es in ein paar Minuten erneut."
                }
        )

    @app.exception_handler(RedisError)
    async def redis_general_exception_handler(request: Request, exc: RedisError):
        logger.error(f"Redis general error globally caught: {exc}")
        return JSONResponse(
            status_code=500,
            content={
                "detail": "Ein unerwarteter Fehler ist aufgetreten. Bitte versuche es später noch einmal."
                }
        )

    @app.exception_handler(asyncio.exceptions.TimeoutError)
    async def timeout_exception_handler(request: Request, exc: asyncio.exceptions.TimeoutError):
        logger.error(f"Timeout error globally caught (Request killed): {exc}")
        return JSONResponse(
            status_code=503,
            content={
                "detail": "Zeitüberschreitung bei der Anfrage. Der Dienst ist derzeit nicht erreichbar."

            }
        )